# Generated by Django 5.0.4 on 2024-04-16 09:52

import core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.get_upload_path, verbose_name='image')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=2, verbose_name='sex')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='nickname')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='biography')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
